check_name: "RuboCop Results"

versions:
  - rubocop
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rspec

rubocop_config_path: ".rubocop.yml"
rubocop_fail_level: "warning"
rubocop_force_exclusion: true
bundle: false
check_scope: "modified"
base_branch: "origin/main"

check_name: "RuboCop Results"
