---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/members":
    get:
      summary: Indexes members
      tags:
      - Members
      produces:
      - application/json
      responses:
        '200':
          description: Members found
          schema:
            type: object
            properties:
              member:
                type: object
                items:
                  "$ref": "#/definitions/Member"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
definitions:
  Member:
    type: object
    properties:
      id:
        type: integer
        example: '100'
      name:
        type: string
        example: test
      description:
        type: string
        example: test
      image:
        type: string
        example: "/img/file.jpg"
